---
- hosts: dell2
  gather_facts: false
#  connection: local
  connection: network_cli

  vars:
    cli:
      username: Dell
      password: P@$$w0rd
    
    vlans:
       20: "Core"
       30: "Monitoring"
       40: "Access"
       50: "Wifi"
  
  tasks:
    - name: "create vlans"
      dellemc.os6.os6_config:
      #ios_config : if the cisco switch
        provider: "{{cli}}"
        lines:
          - name {{item.value}}
        parents:
          - vlan {{item.key}}
      with_dict: "{{vlans}}"

    - name: "show vlan"
      dellos6_command:
        provider: "{{cli}}"
        commands: show vlan
      register: show_vlan
 
    - name: "print output to source"
      debug:
        var=show_vlan.stoud
